### PR TITLE
Feature/phase2

### PR DESCRIPTION
**Pull request by MCFlowMace**
Added Phase 2 support and now also the dictionaries we talked about. That made the constructors much cleaner and also more generic in the way they deal with the parameters. 
Since the `SimConfig` now takes any parameters we also have warnings when unexpected parameters are passed. Dealing with unknown parameters is not strictly necessary, since they are just ignored anyway. But this will prevent user errors due to typos.

### CODE REVIEW

**Comment by charstnut** [comment]
Hi @MCFlowMace, for future commits/features, would it be possible for you to add comments for each function within the class?
It's really hard to understand what the functions do without any comments.. 
For testing, if you think the unittest framework implemented in the `egg_reader` branch is good enough after review, could you modify the phase2 test accordingly? It can just be a test method that runs a P2 simulation and always passes.

**Review by charstnut — CHANGES_REQUESTED** [review]
Please see the comments above

**Comment by MCFlowMace** [comment]
I added documentation for everything in simconfig.py and simulation.py and a unittest for a locust phase 2 simulation as requested. Furthermore, I moved the old "tests" to a directory with examples. And finally, I also added a way for hercules to provide documentation for the simulation parameters on its own!
It's a lot of changes in this single branch now, sorry for that. Let me know if we can merge.

**Review by charstnut — APPROVED** [review]
Perfect! I think we can merge this.

**Pull request merged**
