### PR TITLE
Feature/egg reader improvements

### PR DESCRIPTION
**Pull request by charstnut**
I've rewritten the eggreader so that it now reads the data on a stream by stream basis. The loaded timeseries and FFTs are structured according to [Monarch Doc](https://monarch.readthedocs.io/en/latest/EggStandard.v3.2.0.html#file-structure).

### CODE REVIEW

**Review by Wouter-VDP — COMMENTED** [review]
looks all good with me! Thanks

**Review by MCFlowMace — CHANGES_REQUESTED** [review]
See my comments on slack in private conversation. We need a different dataset layout after data has been read. To summarize my comments from slack: we need a numpy array with shape (n_acquisitions, n_channels, n_records*record_size)

**Comment by charstnut** [comment]
Noted. This will be implemented in a few days.

**Comment by charstnut** [comment]
There are some extra work I've added.. Basically I implemented the unittest framework for the test folder and modifies the existing tests.

**Comment by MCFlowMace** [comment]
Thanks @charstnut, looks good to me. Also the addition of proper unittesting is nice. I made a small change regarding more efficient memory layout for the final data. And I removed the part that added the module to the sys path in the tests. I think it is better to run the tests with the installed module. That way tests are also a check for a proper installation. If you agree with those changes we can merge.

Finally, I would like to suggest for the future that you use the pathlib library in place of calls to os (like os.path.join, or os.mkdir). It is much nicer https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/ .

**Review by MCFlowMace — APPROVED** [review]

**Comment by charstnut** [comment]
Thanks for the review and changes @MCFlowMace! I will take a quick look tomorrow soon and merge the branch. Also sure I will switch to pathlib whenever possible.

**Pull request merged**
